### GET request all Conferences
http://localhost:8080/conferences

### GET request all Reports by Conference id
http://localhost:8080/conferences/3/talks

### POST request to add a new Conference
POST http://localhost:8080/conferences
Content-Type: application/json

  {
    "name": "Курсы языковой школы MasterCLASS",
    "topic": "Английский для дошкольников",
    "dateStart": "2020-05-22",
    "amountParticipants":100
  }

### PUT request to edit an existing Conference
PUT http://localhost:8080/conferences/12
Content-Type: application/json

{
  "name": "MEDICAL DEVICE FORUM 2020_V3",
  "topic": "Влияние Регламента о медицинских изделиях (MDR) на производителей. Новые обязательства для импортеров и дистрибьюторов. И многое другое.",
  "dateStart": "2020-05-05",
  "amountParticipants":150
}

### POST request to add a Report to the Conference
POST http://localhost:8080/conferences/3/talks
Content-Type: application/json

{
  "name": "Программирование в Java",
  "description": "Семинар, 16 академических часов, online-трансляция",
  "typeReport": "MASTER_CLASS",
  "reporter": "Король Р.В._2"
}

###
