apiVersion: v1
kind: Pod
metadata:
  name: kuard
  labels:
    app: kuard
spec:
  initContainers:
    - name: init-kuard
      image: hello-world
      command: ['sh', '-c', 'echo The app is running! && sleep 6']
  containers:
      - livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthy
            port: 8080
        name: liveness
        image: gcr.io/kuar-demo/kuard-amd64:1
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
  restartPolicy: Always
